services:
  laravel-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
      - "8080:80"
    command: |
      sh -c "chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache &&
             chmod -R 775 /var/www/html/storage &&
             chmod -R 775 /var/www/html/bootstrap/cache &&
             apache2-foreground"
    volumes:
      - ./backend:/var/www/html
      - ./.env:/var/www/html/.env
    networks:
      - app-network
    depends_on:
      - db

  nextjs-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nextjs-app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./frontend:/app
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
